# Generated by Django 2.1.15 on 2020-06-03 13:45

import ceos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ceos', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='reviews',
            field=models.ManyToManyField(related_name='orderedstore', through='reviews.Review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plusmenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceos.StoreMenu'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='store',
            field=models.ForeignKey(on_delete=models.SET(ceos.models.get_sentinel_store), to='ceos.Store'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(ceos.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
