# Generated by Django 2.1.15 on 2020-05-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceos', '0002_auto_20200525_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='order_condition',
            field=models.IntegerField(choices=[(0, '결제 대기'), (1, '결제 완료'), (2, '준비중'), (3, '완료')], default=0),
        ),
    ]
